### ISSUE TITLE
_class field generated by Spring Data Arango causing ClassNotFoundException

### ISSUE THREAD

**Issue by gmjordan** [ArangoDB-Community/arangodb-graphql-spring-boot-starter#3]
First, great work and appreciate the time and effort that went into this library.

I am using spring data arango to persist/modify the database (since mutations aren't available yet in the graphql library) and plan to use arango-graphql for the main UI to deliver the majority of the reads.

When testing a query via altair, I received this message:

`Exception while fetching data (/getClient) : com.arangodb.velocypack.exception.VPackParserException: com.arangodb.velocypack.exception.VPackParserException: java.lang.ClassNotFoundException: com.model.Person`

It seems the "_class" property, which gets generated via the [ArangoConfiguration](https://github.com/arangodb/spring-data/blob/master/src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java), is added for inheritance support.  So, as a workaround/fix, I override the method like so:

from

```
 default ArangoTypeMapper arangoTypeMapper() throws Exception {
        return new DefaultArangoTypeMapper(this.typeKey(), this.arangoMappingContext());
    }

```

to (changing **_this.typeKey()_** to **_null_**)

```
@Override
    public ArangoTypeMapper arangoTypeMapper() throws Exception {
        return new DefaultArangoTypeMapper(null, this.arangoMappingContext());
    }
```
then "_class" is not persisted and the graph query works as expected.   

- Will this override present any problems other than possible inheritance issues?
- Is there a better way to address this?

**Comment by colinfindlay** [comment]
Thanks Greg. Appreciate your feedback.

I was able to replicate this easily by manually adding a "_class" attribute to a document. After a quick look I think the problem lies not with Arango Spring Data or the Arango GraphQL Starter but with the java-velocypack implementation.

If you took the Arango GraphQL library out of the mix and imagine you had two applications, app A using the Spring Data support to write instances of com.model.Person to a collection, and app B reading these from the collection using the Java driver, but without com.model.Person on the classpath, I think the second application would fail in the same way because of the "_class" in the document which doesn't seem right to me. I don't want readers of my collection to be coupled to specific Java classes. I would imagine I would still want to interact with the document as a BaseDocument, or potentially represent it as a different class all together from an application that may not have the original class used at write time on the classpath.

My view would be that the private VPack.determineType(VPackSlice vpack, Type type) method would be better off returning the default BaseDocument type if the Class.forName(...) fails, rather than chaining and throwing the ClassNotFoundException. This would allow for App B to function in the scenario above, and eliminate the issue you are facing. 

The other possible solution is to configure the deserialization on the ArangoDB.Builder on your client side to ignore the type key, which you could do by overriding the bean provided by the starter or we could change the starter to do this by default but I think the right thing to do would be to change the java-velocypack implementation as I described above, and therefore it might be worth raising this issue against java-velocypack and linking to this one to avoid having to work around it either in your app, or in the GraphQL starter.

**Comment by gmjordan** [comment]
good idea, @colinfindlay.  short term, I think overriding works. longer term, changing the implementation would be best.  closing this one out.
